config/routes.rb
Rails.application.routes.draw do
  get "help", to: "pages#help"
  # Defines the root path route ("/")
  root "recipes#index"

  # Routes for user sign-up and profile editing
  # get "sign_up", to: "users#new"
  # get "profile", to: "users#edit"

  resources :users do
    resources :recipes, controller: "users/recipes", only: [ :index ] do
      collection do
        # Defines GET /users/:user_id/recipes/cookbook (to show the form)
        get :cookbook
        # Defines POST /users/:user_id/recipes/cookbook (to generate the PDF)
        post :cookbook, action: :create_cookbook
      end
    end
  end

  # Routes for session management (login/logout)
  # This one line creates all the necessary routes for logging in and out.
  # GET    /session/new  -> sessions#new
  # POST   /session      -> sessions#create
  # DELETE /session      -> sessions#destroy
  resource :session, only: [:new, :create, :destroy]

  # Routes for password reset
  resources :passwords, only: [:new, :create, :edit, :update], param: :token

  # Recipe routes
  resources :recipes do
    get "pdf", on: :member
    get "import", on: :collection
    post "import_from_url", on: :collection
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "Recipe Box" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.js" xintegrity="sha512-8RnEqURPUc5aqFEN04aQEiPlSAdE0jlFS/9iGgUyNtwFnSKCXhmB6ZTNl7LnDtDWKabJIASzXrzD0K+LYexU9g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.css" xintegrity="sha512-uf06llspW44/LZpHzHT6qBOIVODjWtv4MxCricRxkzvopAlSWnTf6hpZTFxuuZcuNE9CBQhqE0Seu1CoRk84nQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="layout">
<% if flash[:alert] %>
  <div class="flash flash--alert">
    <p class="flash__message"><%= flash[:alert] %></p>
    <a href="#" class="flash__close">&times;</a>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="flash flash--notice">
    <p class="flash__message"><%= flash[:notice] %></p>
    <a href="#" class="flash__close">&times;</a>
  </div>
<% end %>

<nav class="navbar">
  <h1 class="navbar__brand"><%= link_to "Recipe Box", root_path, class: "navbar__brand-link" %></h1>
  <ul class="navbar__nav navbar__nav--primary">
<!--    <li class="navbar__nav-item"><%#= link_to "Recipes", recipes_path, class: "navbar__nav-link" %></li>-->
  </ul>
  <ul class="navbar__nav navbar__nav--secondary">
    <% if authenticated? %>
      <li class="navbar__nav-item"><%= link_to "New Recipe", new_recipe_path, class: "navbar__nav-link" %></li>
      <li class="navbar__nav-item"><%= link_to Current.user.name, user_path(Current.user), class: "navbar__nav-link" %></li>
    <% else %>
      <li class="navbar__nav-item"><%= link_to "Sign up", new_user_path, class: "navbar__nav-link" %></li>
      <li class="navbar__nav-item"><%= link_to "Sign in", new_session_path, class: "navbar__nav-link" %></li>
    <% end %>
  </ul>
</nav>

<main class="main">
  <%= yield %>
</main>
</body>
</html>